import type { Membership, Organization, Subscription, User } from "./types";

// Données fictives mais réalistes — voir README.md § Fidélité. À remplacer par de vraies
// requêtes (Supabase ou autre, décision à prendre séparément) module par module. Ce fichier
// fait tourner l'architecture commune (sélecteur d'organisation, navigation, permissions) en
// attendant la couche de données réelle.

export const mockUser: User = {
  id: "user-sophie",
  firstName: "Sophie",
  lastName: "Martin",
  email: "sophie.martin@fcfontainebleau.fr",
  jobTitle: "Responsable communication",
  locale: "fr",
  theme: "dark",
  mfaEnabled: false,
  onboardingStep: 10,
  onboardingCompletedAt: "2026-06-12T09:00:00.000Z",
};

export const mockOrganizations: Organization[] = [
  {
    id: "org-fcf",
    type: "club",
    name: "FC Fontainebleau",
    address: "Stade Pierre-Bardin, 77300 Fontainebleau",
    siret: "812 456 789 00021",
    instagramHandle: "@fcfontainebleau",
    teamCount: 6,
    memberCount: 142,
    accountManagerId: "sv-theo-marchand",
    createdAt: "2025-08-01T00:00:00.000Z",
  },
  {
    id: "org-usv",
    type: "club",
    name: "US Varenne",
    address: "Complexe sportif, 77130 Varenne",
    teamCount: 4,
    memberCount: 96,
    accountManagerId: "sv-theo-marchand",
    communityManagerId: "sv-nina-berger",
    createdAt: "2025-11-03T00:00:00.000Z",
  },
  {
    id: "org-lucas",
    type: "player",
    name: "Lucas Mendes",
    parentOrganizationId: "org-fcf",
    accountManagerId: "sv-theo-marchand",
    createdAt: "2025-08-14T00:00:00.000Z",
  },

  // Organisations ajoutées pour couvrir les treize expériences du README (§ Les treize
  // expériences) qui n'existaient pas encore dans le mock : parent, sponsor, CM externe,
  // académie, coach, structure générique, événement, joueur indépendant. Voir § 5, § 10, § 20,
  // § 21 de ACTIONS.md pour les écrans qui en dépendent.
  {
    id: "org-fournier",
    type: "parent",
    name: "Famille Fournier",
    accountManagerId: "sv-theo-marchand",
    createdAt: "2025-09-02T00:00:00.000Z",
  },
  {
    id: "org-ninaberger",
    type: "cm_agency",
    name: "Studio Nina Berger",
    address: "18 rue des Tanneurs, 77300 Fontainebleau",
    siret: "901 234 567 00014",
    instagramHandle: "@studioninaberger",
    accountManagerId: "sv-theo-marchand",
    createdAt: "2025-10-01T00:00:00.000Z",
  },
  {
    id: "org-varenneauto",
    type: "sponsor",
    name: "Varenne Auto",
    address: "Zone artisanale, 77130 Varenne",
    siret: "784 512 963 00028",
    accountManagerId: "sv-theo-marchand",
    createdAt: "2025-11-10T00:00:00.000Z",
  },
  {
    id: "org-gatinais",
    type: "generic",
    name: "Ligue du Gâtinais",
    address: "12 avenue de la République, 45200 Montargis",
    accountManagerId: "sv-theo-marchand",
    createdAt: "2025-07-20T00:00:00.000Z",
  },
  {
    id: "org-elitesportcamp",
    type: "academy",
    name: "Elite Sport Camp",
    address: "Base de loisirs, 77000 Vaux-le-Pénil",
    teamCount: 3,
    memberCount: 58,
    accountManagerId: "sv-theo-marchand",
    createdAt: "2025-12-05T00:00:00.000Z",
  },
  {
    id: "org-eliteacademy",
    type: "academy",
    name: "Elite Academy",
    address: "Centre sportif régional, 77000 Melun",
    instagramHandle: "@eliteacademy77",
    teamCount: 8,
    memberCount: 190,
    accountManagerId: "sv-theo-marchand",
    communityManagerId: "sv-nina-berger",
    createdAt: "2025-09-15T00:00:00.000Z",
  },
  {
    id: "org-chrisperformance",
    type: "coach",
    name: "Chris Performance",
    instagramHandle: "@chrisperformance",
    accountManagerId: "sv-theo-marchand",
    communityManagerId: "sv-nina-berger",
    createdAt: "2025-10-20T00:00:00.000Z",
  },
  {
    id: "org-theolambert",
    type: "coach",
    name: "Coaching Théo Lambert",
    instagramHandle: "@coaching.theolambert",
    accountManagerId: "sv-theo-marchand",
    createdAt: "2026-01-08T00:00:00.000Z",
  },
  {
    id: "org-tournoirentree",
    type: "event",
    name: "Tournoi de la Rentrée",
    address: "Complexe sportif, 77300 Fontainebleau",
    accountManagerId: "sv-theo-marchand",
    createdAt: "2026-08-01T00:00:00.000Z",
  },
  {
    id: "org-elitecup",
    type: "event",
    name: "Elite Cup 2026",
    address: "Stade départemental, 77000 Melun",
    instagramHandle: "@elitecup2026",
    accountManagerId: "sv-theo-marchand",
    communityManagerId: "sv-nina-berger",
    createdAt: "2026-05-01T00:00:00.000Z",
  },
  {
    id: "org-amine",
    type: "player",
    name: "Projet Amine Kaci",
    accountManagerId: "sv-theo-marchand",
    createdAt: "2026-02-11T00:00:00.000Z",
  },
];

export const mockMemberships: Membership[] = [
  { id: "m1", userId: "user-sophie", organizationId: "org-fcf", role: "communication_manager", teamScope: [], capabilities: [], status: "active" },
  { id: "m2", userId: "user-sophie", organizationId: "org-usv", role: "communication_manager", teamScope: [], capabilities: [], status: "active" },
  { id: "m3", userId: "user-sophie", organizationId: "org-lucas", role: "player", teamScope: [], capabilities: [], status: "active" },

  // Mêmes treize expériences — un même utilisateur peut appartenir à plusieurs espaces
  // (README.md § Les treize expériences). Sophie porte ici tous les profils de démonstration.
  { id: "m4", userId: "user-sophie", organizationId: "org-fournier", role: "parent", teamScope: [], capabilities: [], status: "active" },
  { id: "m5", userId: "user-sophie", organizationId: "org-ninaberger", role: "owner", teamScope: [], capabilities: [], status: "active" },
  { id: "m6", userId: "user-sophie", organizationId: "org-varenneauto", role: "partner", teamScope: [], capabilities: [], status: "active" },
  { id: "m7", userId: "user-sophie", organizationId: "org-gatinais", role: "admin", teamScope: [], capabilities: [], status: "active" },
  { id: "m8", userId: "user-sophie", organizationId: "org-elitesportcamp", role: "manager", teamScope: [], capabilities: [], status: "active" },
  { id: "m9", userId: "user-sophie", organizationId: "org-eliteacademy", role: "manager", teamScope: [], capabilities: [], status: "active" },
  { id: "m10", userId: "user-sophie", organizationId: "org-chrisperformance", role: "owner", teamScope: [], capabilities: [], status: "active" },
  { id: "m11", userId: "user-sophie", organizationId: "org-theolambert", role: "owner", teamScope: [], capabilities: [], status: "active" },
  { id: "m12", userId: "user-sophie", organizationId: "org-tournoirentree", role: "event_admin", teamScope: [], capabilities: [], status: "active" },
  { id: "m13", userId: "user-sophie", organizationId: "org-elitecup", role: "event_admin", teamScope: [], capabilities: [], status: "active" },
  { id: "m14", userId: "user-sophie", organizationId: "org-amine", role: "player", teamScope: [], capabilities: [], status: "active" },
];

export const mockSubscriptions: Record<string, Subscription> = {
  "org-fcf": {
    id: "sub-fcf",
    organizationId: "org-fcf",
    planCode: "club_plus_performance",
    status: "active",
    startsAt: "2025-09-01",
    renewsAt: "2026-09-01",
    commitmentMonths: 12,
    noticeMonths: 2,
    creditsRemaining: 26,
    creditsReserved: 3,
    presencesUsed: 3,
    storageUsedBytes: 6_400_000_000,
    storageQuotaBytes: 10_000_000_000,
  },
  "org-usv": {
    id: "sub-usv",
    organizationId: "org-usv",
    planCode: "full_communication",
    status: "active",
    startsAt: "2025-11-03",
    renewsAt: "2026-11-03",
    commitmentMonths: 12,
    noticeMonths: 2,
    creditsRemaining: 0,
    creditsReserved: 0,
    presencesUsed: 3,
    storageUsedBytes: 9_800_000_000,
    storageQuotaBytes: 20_000_000_000,
  },
  "org-lucas": {
    id: "sub-lucas",
    organizationId: "org-lucas",
    planCode: "club_access",
    status: "active",
    startsAt: "2025-08-14",
    renewsAt: "2026-08-14",
    commitmentMonths: 0,
    noticeMonths: 0,
    creditsRemaining: 1,
    creditsReserved: 0,
    presencesUsed: 0,
    storageUsedBytes: 400_000_000,
    storageQuotaBytes: 2_000_000_000,
  },

  // Abonnements des organisations ajoutées ci-dessus — offre reprise telle quelle du tableau
  // README.md § Les treize expériences.
  "org-fournier": {
    id: "sub-fournier",
    organizationId: "org-fournier",
    planCode: "club_access",
    status: "active",
    startsAt: "2025-09-02",
    renewsAt: "2026-09-02",
    commitmentMonths: 0,
    noticeMonths: 0,
    creditsRemaining: 2,
    creditsReserved: 0,
    presencesUsed: 0,
    storageUsedBytes: 250_000_000,
    storageQuotaBytes: 2_000_000_000,
  },
  "org-ninaberger": {
    id: "sub-ninaberger",
    organizationId: "org-ninaberger",
    planCode: "club_plus_start",
    status: "active",
    startsAt: "2025-10-01",
    renewsAt: "2026-10-01",
    commitmentMonths: 12,
    noticeMonths: 2,
    creditsRemaining: 6,
    creditsReserved: 1,
    presencesUsed: 1,
    storageUsedBytes: 3_100_000_000,
    storageQuotaBytes: 8_000_000_000,
  },
  "org-varenneauto": {
    id: "sub-varenneauto",
    organizationId: "org-varenneauto",
    planCode: "club_access",
    status: "active",
    startsAt: "2025-11-10",
    renewsAt: "2026-11-10",
    commitmentMonths: 0,
    noticeMonths: 0,
    creditsRemaining: 3,
    creditsReserved: 0,
    presencesUsed: 0,
    storageUsedBytes: 120_000_000,
    storageQuotaBytes: 2_000_000_000,
  },
  "org-gatinais": {
    id: "sub-gatinais",
    organizationId: "org-gatinais",
    planCode: "one_off",
    status: "active",
    startsAt: "2026-06-01",
    renewsAt: "2026-06-01",
    commitmentMonths: 0,
    noticeMonths: 0,
    creditsRemaining: 1,
    creditsReserved: 0,
    presencesUsed: 1,
    storageUsedBytes: 900_000_000,
    storageQuotaBytes: 2_000_000_000,
  },
  "org-elitesportcamp": {
    id: "sub-elitesportcamp",
    organizationId: "org-elitesportcamp",
    planCode: "one_off",
    status: "active",
    startsAt: "2025-12-05",
    renewsAt: "2026-12-05",
    commitmentMonths: 12,
    noticeMonths: 2,
    creditsRemaining: 0,
    creditsReserved: 0,
    presencesUsed: 0,
    storageUsedBytes: 1_800_000_000,
    storageQuotaBytes: 5_000_000_000,
  },
  "org-eliteacademy": {
    id: "sub-eliteacademy",
    organizationId: "org-eliteacademy",
    planCode: "full_communication",
    status: "active",
    startsAt: "2025-09-15",
    renewsAt: "2026-09-15",
    commitmentMonths: 12,
    noticeMonths: 2,
    creditsRemaining: 0,
    creditsReserved: 0,
    presencesUsed: 7,
    storageUsedBytes: 14_200_000_000,
    storageQuotaBytes: 25_000_000_000,
  },
  "org-chrisperformance": {
    id: "sub-chrisperformance",
    organizationId: "org-chrisperformance",
    planCode: "full_communication",
    status: "active",
    startsAt: "2025-10-20",
    renewsAt: "2026-10-20",
    commitmentMonths: 12,
    noticeMonths: 2,
    creditsRemaining: 0,
    creditsReserved: 0,
    presencesUsed: 4,
    storageUsedBytes: 5_600_000_000,
    storageQuotaBytes: 15_000_000_000,
  },
  "org-theolambert": {
    id: "sub-theolambert",
    organizationId: "org-theolambert",
    planCode: "club_plus_start",
    status: "active",
    startsAt: "2026-01-08",
    renewsAt: "2027-01-08",
    commitmentMonths: 12,
    noticeMonths: 2,
    creditsRemaining: 4,
    creditsReserved: 0,
    presencesUsed: 0,
    storageUsedBytes: 900_000_000,
    storageQuotaBytes: 8_000_000_000,
  },
  "org-tournoirentree": {
    id: "sub-tournoirentree",
    organizationId: "org-tournoirentree",
    planCode: "one_off",
    status: "active",
    startsAt: "2026-08-01",
    renewsAt: "2026-08-01",
    commitmentMonths: 0,
    noticeMonths: 0,
    creditsRemaining: 1,
    creditsReserved: 0,
    presencesUsed: 0,
    storageUsedBytes: 0,
    storageQuotaBytes: 2_000_000_000,
  },
  "org-elitecup": {
    id: "sub-elitecup",
    organizationId: "org-elitecup",
    planCode: "full_communication",
    status: "active",
    startsAt: "2026-05-01",
    renewsAt: "2027-05-01",
    commitmentMonths: 12,
    noticeMonths: 2,
    creditsRemaining: 0,
    creditsReserved: 0,
    presencesUsed: 1,
    storageUsedBytes: 2_100_000_000,
    storageQuotaBytes: 15_000_000_000,
  },
  "org-amine": {
    id: "sub-amine",
    organizationId: "org-amine",
    planCode: "club_access",
    status: "active",
    startsAt: "2026-02-11",
    renewsAt: "2027-02-11",
    commitmentMonths: 0,
    noticeMonths: 0,
    creditsRemaining: 0,
    creditsReserved: 0,
    presencesUsed: 0,
    storageUsedBytes: 60_000_000,
    storageQuotaBytes: 2_000_000_000,
  },
};
